# Generated by Django 4.2.6 on 2023-12-09 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='probecalibration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_id', models.CharField(max_length=50, unique=True)),
                ('low_ref', models.JSONField(default=list)),
                ('low_count', models.JSONField(default=list)),
                ('high_ref', models.JSONField(default=list)),
                ('high_count', models.JSONField(default=list)),
                ('coefficent', models.JSONField(default=list)),
            ],
        ),
    ]
