# Generated by Django 4.2.6 on 2024-01-24 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_sonapariya'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableonedata',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
