# Generated by Django 4.2.6 on 2024-03-04 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_captvalues_sr_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='master',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=100)),
                ('low_mv', models.FloatField()),
                ('high_mv', models.FloatField()),
                ('probe_no', models.IntegerField()),
                ('nominal', models.FloatField()),
            ],
        ),
    ]
