# Generated by Django 4.2.6 on 2023-12-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_tabledata_delete_getvalues'),
    ]

    operations = [
        migrations.CreateModel(
            name='RowData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=100)),
                ('row_index', models.IntegerField()),
                ('values', models.TextField()),
            ],
        ),
    ]
