# Generated by Django 4.2.6 on 2024-03-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_master'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasteringData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_no', models.IntegerField()),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('parameter_name', models.CharField(max_length=100)),
            ],
        ),
    ]
