# Generated by Django 4.2.6 on 2024-01-26 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_parametervalue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parametervalue',
            name='analog_zero',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='high_mv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='low_mv',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='parametervalue',
            name='reference_value',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
