# Generated by Django 4.2.6 on 2024-03-05 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_masteringdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_no', models.CharField(max_length=50)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('parameter_name', models.CharField(max_length=100)),
                ('selected_value', models.CharField(max_length=100)),
                ('selected_mastering', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
