# Generated by Django 4.2.6 on 2024-03-06 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_masterdata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='probe_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='selected_mastering',
            field=models.IntegerField(),
        ),
    ]
