# Generated by Django 4.2.6 on 2023-12-15 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_itemdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='verData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_id', models.CharField(max_length=100)),
                ('row_index', models.IntegerField()),
                ('column_1', models.CharField(max_length=100)),
                ('column_2', models.CharField(max_length=100)),
            ],
        ),
    ]
