# Generated by Django 4.2.6 on 2024-01-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_parametervalue_analog_zero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='captvalues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_id', models.CharField(max_length=255)),
                ('parameter_name', models.CharField(max_length=255)),
                ('single_radio', models.BooleanField(default=False)),
                ('analog_zero', models.FloatField(blank=True, null=True)),
                ('reference_value', models.FloatField(blank=True, null=True)),
                ('double_radio', models.BooleanField(default=False)),
                ('high_mv', models.FloatField(blank=True, null=True)),
                ('low_mv', models.FloatField(blank=True, null=True)),
                ('probe_no', models.FloatField()),
                ('measurement_mode', models.CharField(max_length=50)),
                ('nominal', models.FloatField()),
                ('usl', models.FloatField()),
                ('lsl', models.FloatField()),
                ('mastering', models.FloatField()),
                ('step_no', models.FloatField()),
                ('hide_checkbox', models.BooleanField(default=False)),
            ],
        ),
    ]
