# Generated by Django 4.2.6 on 2024-01-29 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_captvalues'),
    ]

    operations = [
        migrations.DeleteModel(
            name='parameterValue',
        ),
        migrations.AddField(
            model_name='tableonedata',
            name='hide_box',
            field=models.BooleanField(default=False),
        ),
    ]
