# Generated by Django 4.2.6 on 2023-12-15 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_verdata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='verdata',
            old_name='column_1',
            new_name='customer_name',
        ),
        migrations.RenameField(
            model_name='verdata',
            old_name='column_2',
            new_name='part_name',
        ),
        migrations.RemoveField(
            model_name='verdata',
            name='row_index',
        ),
        migrations.RemoveField(
            model_name='verdata',
            name='table_id',
        ),
    ]
