# Generated by Django 4.2.6 on 2023-12-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_rename_column_1_verdata_customer_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='sarkmodu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_name', models.CharField(max_length=100)),
                ('customer_name', models.CharField(max_length=100)),
                ('part_model', models.CharField(max_length=100)),
                ('part_no', models.CharField(max_length=100)),
            ],
        ),
    ]
