# Generated by Django 4.2.6 on 2024-03-06 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_masterdata_date_time_alter_masterdata_probe_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='date_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='probe_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='selected_mastering',
            field=models.IntegerField(),
        ),
    ]
