# Generated by Django 4.2.6 on 2024-01-29 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_delete_parametervalue_tableonedata_hide_box'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tableonedata',
            old_name='hide_box',
            new_name='is_selected',
        ),
    ]
