# Generated by Django 4.2.6 on 2024-03-06 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_masterdata_date_time_alter_masterdata_probe_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='probe_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='selected_mastering',
            field=models.CharField(max_length=100),
        ),
    ]
