# Generated by Django 4.2.6 on 2023-12-16 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_barkmod'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TraceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_index', models.IntegerField()),
                ('column_index', models.IntegerField()),
                ('value', models.CharField(max_length=255)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.item')),
            ],
        ),
        migrations.DeleteModel(
            name='barkmod',
        ),
        migrations.DeleteModel(
            name='RowData',
        ),
        migrations.DeleteModel(
            name='sarkmodu',
        ),
        migrations.DeleteModel(
            name='TableData',
        ),
        migrations.DeleteModel(
            name='verData',
        ),
    ]
