# Generated by Django 4.2.6 on 2024-03-06 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_masterdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
