# Generated by Django 4.2.6 on 2023-12-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_tablefivedata_tablefourdata_tableonedata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tablefivedata',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='tablefourdata',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='tableonedata',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='tablethreedata',
            name='sr_no',
        ),
        migrations.RemoveField(
            model_name='tabletwodata',
            name='sr_no',
        ),
    ]
