# Generated by Django 4.2.6 on 2024-03-07 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_exivalues'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exivalues',
            name='probe_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='exivalues',
            name='selected_mastering',
            field=models.IntegerField(),
        ),
    ]
