# Generated by Django 4.2.6 on 2024-01-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_saveddata_delete_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
                ('part_model', models.CharField(max_length=255)),
            ],
        ),
    ]
