# Generated by Django 4.2.6 on 2024-03-07 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_exivalues_probe_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='masterdata',
            name='probe_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='selected_mastering',
            field=models.IntegerField(),
        ),
    ]
