# Generated by Django 4.2.6 on 2024-01-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_savedparameter'),
    ]

    operations = [
        migrations.CreateModel(
            name='paraname',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter_name', models.CharField(max_length=255)),
            ],
        ),
    ]
