# Generated by Django 4.2.6 on 2024-03-07 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_alter_masterdata_probe_no_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='exiValues',
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='probe_no',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='masterdata',
            name='selected_mastering',
            field=models.CharField(max_length=100),
        ),
    ]
