# Generated by Django 4.2.6 on 2024-03-07 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_delete_exivalues_alter_masterdata_probe_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='contiValues',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probe_no', models.CharField(max_length=100)),
                ('a', models.FloatField()),
                ('b', models.FloatField()),
                ('parameter_name', models.CharField(max_length=100)),
                ('selected_value', models.CharField(max_length=100)),
                ('selected_mastering', models.CharField(max_length=100)),
                ('date_time', models.CharField(max_length=30)),
            ],
        ),
    ]
